version: "3"

services:
  app:
    build: .
    tty: true
    volumes:
      - ./src:/opt/app
      - ./src/node_modules:/opt/app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "yarn dev"
