version: "3"

services:
  app:
    container_name: app
    build: .
    tty: true
    volumes:
      - ./src:/opt/app
    environment:
      - NODE_ENV=development
      - ./src/node_modules:/opt/app/node_modules
    ports:
      - "3000:3000"
      - "6006:6006"
    command: sh -c "yarn dev"
