# docker-compose周りで読んでおきたい記事
# => https://qiita.com/yuki_0920/items/dc3f32667d004979cc5a
# => https://qiita.com/prgseek/items/e557a371d7bd1f57b9b1#-docker-composeyml

version: "3"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    tty: true
    volumes:
      - ./src:/opt/app
      - ./src/node_modules:/opt/app/node_modules
    ports:
      - "3000:3000"
      # - "6006:6006"
    command: sh -c "yarn dev"

  # storybook:
  #   container_name: storybook
  #   build:
  #     context: .
  #     dockerfile: ./docker/storybook/Dockerfile
  #   tty: true
  #   ports:
  #     - "6006:6006"
  #   command: sh -c "yarn storybook"
