version: "3"

services:
  app:
    container_name: app
    build: .
    tty: true
    volumes:
      - ./src:/opt/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    command: sh -c "yarn dev"
